# Generated by Django 5.2.7 on 2025-10-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='time',
            field=models.IntegerField(default=1, verbose_name='Время фильма'),
            preserve_default=False,
        ),
    ]
