# Generated by Django 5.2.7 on 2025-10-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_film_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='time',
            field=models.IntegerField(default=120, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
