# Generated by Django 5.2.7 on 2025-10-31 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_film_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='time',
        ),
    ]
