# Generated by Django 5.2.7 on 2025-10-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_film_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.CharField(default=2, max_length=100, verbose_name='Старана'),
            preserve_default=False,
        ),
    ]
